title: [Param Bole]
logo: "/images/main_pic.jpg"
github:
  is_project_page: false
description: > # your text below (remove <br> elements if you don't need line breaks)
  [ Accidental Engineer ]  
  <br><br>
  <a href="https://www.linkedin.com/in/parambole/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/parambole">View My GitHub Profile</a>
  <br><br>
  <a href="https://medium.com/@parambole04">View My Medium Blog</a
theme: jekyll-theme-minimal
